### ISSUE TITLE
New install on osx with Meteor 1.2.1 crash from missing package 'fibers'

### ISSUE THREAD

**Issue by mcheck** [themeteorchef/base#118]
From ```npm start``` app says it is crashing.

```
W20160315-19:41:49.491(-5)? (STDERR)          
W20160315-19:41:49.492(-5)? (STDERR) module.js:340
W20160315-19:41:49.492(-5)? (STDERR)     throw err;
W20160315-19:41:49.492(-5)? (STDERR)           ^
W20160315-19:41:49.492(-5)? (STDERR) Error: Cannot find module 'fibers'
W20160315-19:41:49.492(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160315-19:41:49.492(-5)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160315-19:41:49.493(-5)? (STDERR)     at Module.require (module.js:364:17)
W20160315-19:41:49.493(-5)? (STDERR)     at require (module.js:380:17)
W20160315-19:41:49.493(-5)? (STDERR)     at Object.<anonymous> (/Users/once/meteor/base-app/.meteor/local/build/programs/server/boot.js:1:75)
W20160315-19:41:49.493(-5)? (STDERR)     at Module._compile (module.js:456:26)
W20160315-19:41:49.493(-5)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160315-19:41:49.493(-5)? (STDERR)     at Module.load (module.js:356:32)
W20160315-19:41:49.494(-5)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160315-19:41:49.494(-5)? (STDERR)     at Module.require (module.js:364:17)
```

**Comment by mcheck** [comment]
After reading about others with same ```'fibers'``` problem, and it happening to me in several new applications, I found that a simple uninstall and reinstall fixed the issue. The ```curl``` install will first uninstall before installing.

```curl https://install.meteor.com/ | sh```

Odd thing was that the fibers issue just started happening without warning, and only to some meteor applications. But now all is working again.
