### ISSUE TITLE
Exited with code : 8

### ISSUE THREAD

**Issue by Cleanshooter** [themeteorchef/base#138]
Fresh git clone
Ran 'npm install' from base 
Ran meteor
won't start, error message follows:

`=> Started proxy.
=> Started MongoDB.
W20160504-08:16:24.231(-5)? (STDERR)
W20160504-08:16:24.231(-5)? (STDERR) C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\boot.js:324
W20160504-08:16:24.231(-5)? (STDERR) }).run();
W20160504-08:16:24.231(-5)? (STDERR)    ^
W20160504-08:16:24.231(-5)? (STDERR) Error: Can't find npm module 'babel-runtime/helpers/typeof'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160504-08:16:24.231(-5)? (STDERR)     at Object.Npm.require (C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\boot.js:195:17)
W20160504-08:16:24.231(-5)? (STDERR)     at options.fallback (packages/modules-runtime/packages/modules-runtime.js:396:1)
W20160504-08:16:24.231(-5)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:88:1)
W20160504-08:16:24.231(-5)? (STDERR)     at meteorInstall.node_modules.meteor.webapp.webapp_server.js (C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\packages\webapp.js:33:16)
W20160504-08:16:24.231(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:148:1)
W20160504-08:16:24.231(-5)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:82:1)
W20160504-08:16:24.231(-5)? (STDERR)     at C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\packages\webapp.js:843:1
W20160504-08:16:24.231(-5)? (STDERR)     at C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\packages\webapp.js:856:3
W20160504-08:16:24.231(-5)? (STDERR)     at C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\boot.js:283:10
W20160504-08:16:24.231(-5)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8
W20160504-08:17:02.709(-5)? (STDERR)
W20160504-08:17:02.710(-5)? (STDERR) C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\boot.js:324
W20160504-08:17:02.710(-5)? (STDERR) }).run();
W20160504-08:17:02.710(-5)? (STDERR)    ^
W20160504-08:17:02.710(-5)? (STDERR) Error: Can't find npm module 'babel-runtime/helpers/typeof'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160504-08:17:02.710(-5)? (STDERR)     at Object.Npm.require (C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\boot.js:195:17)
W20160504-08:17:02.711(-5)? (STDERR)     at options.fallback (packages/modules-runtime/packages/modules-runtime.js:396:1)
W20160504-08:17:02.711(-5)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:88:1)
W20160504-08:17:02.711(-5)? (STDERR)     at meteorInstall.node_modules.meteor.webapp.webapp_server.js (C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\packages\webapp.js:33:16)
W20160504-08:17:02.711(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:148:1)
W20160504-08:17:02.711(-5)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:82:1)
W20160504-08:17:02.711(-5)? (STDERR)     at C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\packages\webapp.js:843:1
W20160504-08:17:02.712(-5)? (STDERR)     at C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\packages\webapp.js:856:3
W20160504-08:17:02.712(-5)? (STDERR)     at C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submit-rma\.meteor\local\build\programs\server\boot.js:283:10
W20160504-08:17:02.712(-5)? (STDERR)     at Array.forEach (native)`

Running on latest version of node on Windows 10

**Comment by Cleanshooter** [comment]
When I attempt to delete the folder it usually get an error saying that several items in the chimp folder are too long for this operating system.  My guess is that the current babel package is nested to deep in it file structure to be used on Windows.  I've seen this both with meteor packages.

**Comment by Cleanshooter** [comment]
nvm this looks like an NPM error now

**Comment by Cleanshooter** [comment]
Correction this is a massive fail in meteor. https://github.com/meteor/meteor/issues/6918
