### ISSUE TITLE
Application does not start

### ISSUE THREAD

**Issue by focused** [themeteorchef/base#139]
I followed instructions, console prints `App running at: http://localhost:3000/`.
When I open `http://localhost:3000`, I see nothing. When I hit Ctrl+C at console, it shows error:
```
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files '/Users/focused/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/shell-server.js'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.Module._extensions..js (module.js:473:44)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /tools/runners/run-app.js:146:7
    at /Users/focused/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/cleanup.js:24:7
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/focused/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/focused/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/cleanup.js:23:7
    at Object.exports.noYieldsAllowed (/tools/utils/fiber-helpers.js:37:14)
    at runHandlers (/Users/focused/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/cleanup.js:20:16)
    at process.<anonymous> (/Users/focused/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/cleanup.js:32:5)
    at process.g (events.js:180:16)
    at process.emit (events.js:92:17)
    at Signal.wrap.onsignal (node.js:800:46)
```
Mac OS El Captain 10.11.4, node 0.10.44, npm 2.15.0

**Comment by themeteorchef** [comment]
This appears to be an issue with Meteor itself and not Base directly. See a similar report [here](https://github.com/meteor/meteor/issues/6966). Going to close this out but watch for a version bump once there's a patch release from MDG.
