### ISSUE TITLE
node-fibers missing error on chimp-test

### ISSUE THREAD

**Issue by bonnaudc** [themeteorchef/base#151]
Hi everyone,

I can't get chimp testing working out of the box with Base.

Here are the installation commands I followed from `https://themeteorchef.com/base/getting-started/` :

```
git clone https://github.com/themeteorchef/base.git myApp
cd myApp
npm install
```

Whenever I try to run _meteor npm run chimp-test_, I get the following error :

```
/root/workspace/myApp2/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
              ^
Error: `/root/workspace/myApp2/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/root/workspace/myApp2/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/workspace/myApp2/node_modules/xolvio-sync-webdriverio/index.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/workspace/myApp2/node_modules/chimp/dist/lib/session-manager.js:39:38)
    at Module._compile (module.js:456:26)
```

Did I miss something here ?

Thanks for your help 

Cy

**Comment by themeteorchef** [comment]
You didn't! This is a documentation error on my part, apologies. You'll want to run this with a plain `npm run chimp-test` (drop the `meteor` at the start). Updating the docs now :)

**Comment by bonnaudc** [comment]
Hi

Thanks for the quick reply. I now have the following error when running `npm run chimp-test` : 

`[chimp] Running...
selenium-standalone installation [====================] 99% 0.0s/root/workspace/myApp3/node_modules/which/which.js:136
  throw new Error('not found: '+cmd)
  ^

Error: not found: java
    at Function.whichSync [as sync] (/root/workspace/myApp3/node_modules/which/which.js:136:9)
    at Object.start (/root/workspace/myApp3/node_modules/selenium-standalone/lib/start.js:46:27)
    at /root/workspace/myApp3/node_modules/chimp/dist/lib/selenium.js:151:14
    at /root/workspace/myApp3/node_modules/selenium-standalone/lib/install.js:80:5
    at /root/workspace/myApp3/node_modules/selenium-standalone/node_modules/async/lib/async.js:708:13
    at /root/workspace/myApp3/node_modules/selenium-standalone/node_modules/async/lib/async.js:49:16
    at /root/workspace/myApp3/node_modules/selenium-standalone/node_modules/async/lib/async.js:263:32
    at /root/workspace/myApp3/node_modules/selenium-standalone/node_modules/async/lib/async.js:40:16
    at /root/workspace/myApp3/node_modules/selenium-standalone/node_modules/async/lib/async.js:705:17
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "chimp-test"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
`

Any clue ?

**Comment by themeteorchef** [comment]
@bonnaudc It looks like you're missing Java. Try a download [from this link](https://java.com/en/download/) and then run the code again and let me know if it works :)
