### ISSUE TITLE
Error when trying to run "meteor npm start"

### ISSUE THREAD

**Issue by do-n-khanh** [themeteorchef/base#164]
I am new to meteor. I got an error like below. Can you please give the solution? Thanks.

[[[[[ C:\Meteor\sampleapp ]]]]]

=> Started proxy.
=> Started MongoDB.
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:96:12)
    at new Buffer (buffer.js:56:12)
    at increaseBufferIfNecessary (C:\Users\Khanh\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\stream-buffers\lib\writable_streambuffer.js:58:23)
    at [object Object]._write (C:\Users\Khanh\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\stream-buffers\lib\writable_streambuffer.js:65:5)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at [object Object].Writable.write (_stream_writable.js:214:11)
    at Request.ondata (stream.js:31:26)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\Khanh\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\request\request.js:1255:12)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:124:22)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Khanh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Khanh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! application-name@1.0.0 start: `meteor --settings settings-development.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the application-name@1.0.0 start script 'meteor --settings settings-development.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the application-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor --settings settings-development.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs application-name
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls application-name
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Meteor\sampleapp\npm-debug.log

**Comment by balibou** [comment]
Hello !
Did you first do a 'meteor npm install' ?

**Comment by do-n-khanh** [comment]
yes. I did

**Comment by balibou** [comment]
Apparently it's an error with node and windows ... Maybe there's a problem with that environment ... I would try a meteor update but if it doesn't work honestly I don't know :/

**Comment by do-n-khanh** [comment]
Hi, I dont know how, but the error disappear. Now the next error appears. Do you have any suggesion? Thanks.

=> A patch (Meteor 1.4.0.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
C:\Users\Khanh\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Khanh\AppData\Local\.meteor\packages\practicalmeteor_mocha\2.4.5_6\os.json'
    at Error (native)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Khanh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Khanh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! application-name@1.0.0 start: `meteor --settings settings-development.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the application-name@1.0.0 start script 'meteor --settings settings-development.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the application-name package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor --settings settings-development.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs application-name
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls application-name
npm ERR! There is likely additional logging output above.

**Comment by 416serg** [comment]
can you make sure that the docs say `meteor npm install` and not just `npm install` https://themeteorchef.com/base/getting-started/

**Comment by themeteorchef** [comment]
Added `meteor npm install` to docs. If there's something else involved here, feel free to comment/reopen.

**Comment by smdrmaryshaw** [comment]
1
