### ISSUE TITLE
Cannot deploy with mup

### ISSUE THREAD

**Issue by hoangdo94** [themeteorchef/base#187]
Hello there,

Thanks for the awesome boilerplate. I have used it before (from the time flowrouter was being used). Now I start to use it again. It can run flawlessly on my local, but when I try to deploy it to my VPS, I got this problem:

> (node:4572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): > Error: 
> -----------------------------------STDERR-----------------------------------
> ection/pool.js:260:12)
>     at [object Object].g (events.js:260:16)
>     at emitTwo (events.js:87:13)
>     at [object Object].emit (events.js:172:7)
>     at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
>     at Socket.g (events.js:260:16)
>     at emitOne (events.js:77:13)
> 
> > meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> > node npm-rebuild.js
> 

Here is my mup conf file

```
module.exports = {
  servers: {
    one: {
      host: '*******',
      username: '****',
      pem: '*****',
      opts: {
          port: 22,
      },
    }
  },

  meteor: {
    name: '*****',
    path: '../',
    docker: {
      image:'abernix/meteord:base'
    },
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      debug: true,
      cleanAfterBuild: true, // default
    },
    env: {
      ROOT_URL: '****',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    deployCheckWaitTime: 120 //default 10
  },
};

```

How can I solve this problem?

Cheers,

**Comment by hoangdo94** [comment]
Seem like I got something wrong with the mongo config
