### ISSUE TITLE
Error: No metadata files found for isopack

### ISSUE THREAD

**Issue by gitMonks** [themeteorchef/base#214]
Hi 

I get following error when trying to start meteor with "meteor" command. 

Error: No metadata files found for isopack at: /Users/Imran/.meteor/packages/localstorage/.1.0.11.1nbfssy++os+web.browser+web.cordova
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:900:13)
    at /tools/packaging/tropohouse.js:520:19
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Imran/.meteor/packages/meteor-tool/.1.4.0-1.136r4y0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/packaging/tropohouse.js:519:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:454:20)
    at /tools/packaging/tropohouse.js:611:18
    at /tools/utils/buildmessage.js:572:21
    at /Users/Imran/.meteor/packages/meteor-tool/.1.4.0-1.136r4y0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:32:39

Thanks in advance for your help

**Comment by gitMonks** [comment]
Fresh installation of Meteor by simply using "curl https://install.meteor.com/ | sh"  sorted out this issue.

Thanks
