### ISSUE TITLE
Can't add msavin:mongol package

### ISSUE THREAD

**Issue by paul-bo** [themeteorchef/base#73]
I can't add the mongol package. Get an issue. 
Is it due to a conflict with underscore and lodash?

Is this somehow related? https://github.com/msavin/Mongol/issues/48
Tried to add mongol in the beginning or end it does not change.

Perhaps I'm doing something wrong?

```
W20150930-15:09:56.620(2)? (STDERR)           
W20150930-15:09:56.621(2)? (STDERR) /home/ertix/.meteor/packages/meteor-tool/.1.1.9.1l55wcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150930-15:09:56.626(2)? (STDERR) 						throw(ex);
W20150930-15:09:56.626(2)? (STDERR) 						      ^
W20150930-15:09:56.629(2)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-15:09:56.630(2)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-15:09:56.630(2)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-15:09:56.630(2)? (STDERR)     at /home/ertix/meteor_projects/base-dl-01/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20150930-15:09:56.630(2)? (STDERR)     at /home/ertix/meteor_projects/base-dl-01/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20150930-15:09:56.630(2)? (STDERR)     at /home/ertix/meteor_projects/base-dl-01/.meteor/local/build/programs/server/boot.js:242:10
W20150930-15:09:56.630(2)? (STDERR)     at Array.forEach (native)
W20150930-15:09:56.630(2)? (STDERR)     at Function._.each._.forEach (/home/ertix/.meteor/packages/meteor-tool/.1.1.9.1l55wcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-15:09:56.631(2)? (STDERR)     at /home/ertix/meteor_projects/base-dl-01/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

**Comment by themeteorchef** [comment]
This may be an error in Mongol. It doesn't look like it's related to the issue you linked, but this reads like something in the code is trying to access on a non-existent property on an object. 

```
TypeError: Property 'undefined' of object [object Object] is not a function
```

I'll flag this to test and install a copy of Meteor Toys and see what I get on my end.

**Comment by themeteorchef** [comment]
Testing now. Can confirm an install and running the package as expected:

![](http://cl.ly/image/0Q1i3e2j2T2d/Image%202015-10-04%20at%208.14.08%20PM.png)

@paul-bo can you try updating mongol (`meteor update msavin:mongol`) to see if this helps?

**Comment by paul-bo** [comment]
I could not replicate the error again. That's strange but everything is running perfect now. 
Thank you for testing.

**Comment by themeteorchef** [comment]
Cool, glad it's working :) no problemo.
